version: '2'
services:

  # The Application
  app:
    restart: always
    build:
      context: ./docker
      dockerfile: app.dockerfile
    working_dir: /var/www
    container_name: dota_app
    volumes:
      - ./app:/var/www
    env_file:
      - ./app/.env
    environment:
      # debug configurations
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: "client_host=192.168.254.1 mode=debug"
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_MODE: "debug"
      DBGP_IDEKEY: "docker"
    networks:
        - dota

  # The Web Server
  web:
    restart: always
    build:
      context: ./docker
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    ports:
      - 9480:80
    networks:
      - dota


  # The Database
  database:
    image: mysql:8
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - ./dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dota

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
    links:
      - database
    ports:
      - 9481:80
    volumes:
    - /sessions
    networks:
      - dota

  redis:
    image: redis
    networks:
      - dota

networks:
  dota:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.254.0/28
